/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/ibaldin/workspace-serpent/caida/src/main/resources/indl.ttl 
 * @author Auto-generated by schemagen on 12 May 2017 15:09 
 */
public class Indl {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2002/07/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty implementedBy = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#implementedBy" );
    
    public static final ObjectProperty hasComponent = m_model.createObjectProperty( "http://www.science.uva.nl/research/sne/indl#hasComponent" );
    
    public static final ObjectProperty implements_ = m_model.createObjectProperty( "http://www.science.uva.nl/research/sne/indl#implements" );
    
    public static final ObjectProperty partOf = m_model.createObjectProperty( "http://www.science.uva.nl/research/sne/indl#partOf" );
    
    /** <p>the number of cores on a CPU</p> */
    public static final DatatypeProperty cores = m_model.createDatatypeProperty( "http://www.science.uva.nl/research/sne/indl#cores" );
    
    /** <p>cpu architecture</p> */
    public static final DatatypeProperty cpuarch = m_model.createDatatypeProperty( "http://www.science.uva.nl/research/sne/indl#cpuarch" );
    
    /** <p>the speed per core in GHz</p> */
    public static final DatatypeProperty cpuspeed = m_model.createDatatypeProperty( "http://www.science.uva.nl/research/sne/indl#cpuspeed" );
    
    /** <p>size of storage or memory in GB</p> */
    public static final DatatypeProperty size = m_model.createDatatypeProperty( "http://www.science.uva.nl/research/sne/indl#size" );
    
    public static final AnnotationProperty comment = m_model.createAnnotationProperty( "http://www.w3.org/2000/01/rdf-schema#comment" );
    
    public static final OntClass Node = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Node" );
    
    public static final OntClass MemoryComponent = m_model.createClass( "http://www.science.uva.nl/research/sne/indl#MemoryComponent" );
    
    public static final OntClass NodeComponent = m_model.createClass( "http://www.science.uva.nl/research/sne/indl#NodeComponent" );
    
    public static final OntClass ProcessingComponent = m_model.createClass( "http://www.science.uva.nl/research/sne/indl#ProcessingComponent" );
    
    public static final OntClass StorageComponent = m_model.createClass( "http://www.science.uva.nl/research/sne/indl#StorageComponent" );
    
    public static final OntClass VirtualNode = m_model.createClass( "http://www.science.uva.nl/research/sne/indl#VirtualNode" );
    
}
