/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/ibaldin/workspace-serpent/caida/src/main/resources/nml-base.ttl 
 * @author Auto-generated by schemagen on 12 May 2017 15:09 
 */
public class Nml_base {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://www.w3.org/2002/07/owl#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty existsDuring = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#existsDuring" );
    
    public static final ObjectProperty hasInboundPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasInboundPort" );
    
    public static final ObjectProperty hasLabel = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasLabel" );
    
    public static final ObjectProperty hasLabelGroup = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasLabelGroup" );
    
    public static final ObjectProperty hasLink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasLink" );
    
    public static final ObjectProperty hasNode = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasNode" );
    
    public static final ObjectProperty hasOutboundPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasOutboundPort" );
    
    public static final ObjectProperty hasPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasPort" );
    
    public static final ObjectProperty hasService = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasService" );
    
    public static final ObjectProperty hasSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasSink" );
    
    public static final ObjectProperty hasSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasSource" );
    
    public static final ObjectProperty hasTopology = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#hasTopology" );
    
    public static final ObjectProperty implementedBy = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#implementedBy" );
    
    public static final ObjectProperty isAlias = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#isAlias" );
    
    public static final ObjectProperty isSerialCompoundLink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#isSerialCompoundLink" );
    
    public static final ObjectProperty isSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#isSink" );
    
    public static final ObjectProperty isSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#isSource" );
    
    public static final ObjectProperty locatedAt = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#locatedAt" );
    
    public static final ObjectProperty providesLink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#providesLink" );
    
    public static final ObjectProperty providesPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/base/2013/02#providesPort" );
    
    public static final ObjectProperty topObjectProperty = m_model.createObjectProperty( "http://www.w3.org/2002/07/owl#topObjectProperty" );
    
    public static final DatatypeProperty adaptationfunction = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#adaptationfunction" );
    
    public static final DatatypeProperty address = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#address" );
    
    public static final DatatypeProperty alt = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#alt" );
    
    public static final DatatypeProperty encoding = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#encoding" );
    
    public static final DatatypeProperty endtime = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#endtime" );
    
    public static final DatatypeProperty labeltype = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#labeltype" );
    
    public static final DatatypeProperty labelvalue = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#labelvalue" );
    
    public static final DatatypeProperty labelvalues = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#labelvalues" );
    
    public static final DatatypeProperty lat = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#lat" );
    
    public static final DatatypeProperty long_ = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#long" );
    
    public static final DatatypeProperty name = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#name" );
    
    public static final DatatypeProperty starttime = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#starttime" );
    
    public static final DatatypeProperty time = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#time" );
    
    public static final DatatypeProperty unlocode = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#unlocode" );
    
    public static final DatatypeProperty version = m_model.createDatatypeProperty( "http://schemas.ogf.org/nml/base/2013/02#version" );
    
    public static final OntClass AdaptationService = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#AdaptationService" );
    
    public static final OntClass BidirectionalLink = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#BidirectionalLink" );
    
    public static final OntClass BidirectionalPort = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#BidirectionalPort" );
    
    public static final OntClass DeadaptationService = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#DeadaptationService" );
    
    public static final OntClass Group = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Group" );
    
    public static final OntClass Label = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Label" );
    
    public static final OntClass LabelGroup = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#LabelGroup" );
    
    public static final OntClass Lifetime = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Lifetime" );
    
    public static final OntClass Link = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Link" );
    
    public static final OntClass LinkGroup = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#LinkGroup" );
    
    public static final OntClass List = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#List" );
    
    public static final OntClass Location = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Location" );
    
    public static final OntClass NetworkObject = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#NetworkObject" );
    
    public static final OntClass Node = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Node" );
    
    public static final OntClass Port = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Port" );
    
    public static final OntClass PortGroup = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#PortGroup" );
    
    public static final OntClass Service = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Service" );
    
    public static final OntClass SwitchingService = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#SwitchingService" );
    
    public static final OntClass Topology = m_model.createClass( "http://schemas.ogf.org/nml/base/2013/02#Topology" );
    
    public static final OntClass Thing = m_model.createClass( "http://www.w3.org/2002/07/owl#Thing" );
    
}
