/* CVS $Id: $ */
package info.openmultinet.ontology.vocabulary; 
import org.apache.jena.rdf.model.*;
import org.apache.jena.ontology.*;
 
/**
 * Vocabulary definitions from file:/Users/ibaldin/workspace-serpent/caida/src/main/resources/nml-bgp.ttl 
 * @author Auto-generated by schemagen on 18 Oct 2017 15:12 
 */
public class Nml_bgp {
    /** <p>The ontology model that holds the vocabulary terms</p> */
    private static OntModel m_model = ModelFactory.createOntologyModel( OntModelSpec.OWL_MEM, null );
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://schemas.ogf.org/nml/bgp/2017/03#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final ObjectProperty hasCPSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#hasCPSink" );
    
    public static final ObjectProperty hasCPSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#hasCPSource" );
    
    public static final ObjectProperty hasPPSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#hasPPSink" );
    
    public static final ObjectProperty hasPPSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#hasPPSource" );
    
    public static final ObjectProperty isCPSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isCPSink" );
    
    public static final ObjectProperty isCPSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isCPSource" );
    
    public static final ObjectProperty isInboundPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isInboundPort" );
    
    public static final ObjectProperty isOutboundPort = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isOutboundPort" );
    
    public static final ObjectProperty isPPSink = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isPPSink" );
    
    public static final ObjectProperty isPPSource = m_model.createObjectProperty( "http://schemas.ogf.org/nml/bgp/2017/03#isPPSource" );
    
    /** <p>Customer-Provider link in BGP inter-AS topology</p> */
    public static final OntClass CPLink = m_model.createClass( "http://schemas.ogf.org/nml/bgp/2017/03#CPLink" );
    
    /** <p>Provider-Provider link in BGP inter-AS topology</p> */
    public static final OntClass PPLink = m_model.createClass( "http://schemas.ogf.org/nml/bgp/2017/03#PPLink" );
    
}
